'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default

    '''<summary>
    '''inputUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputUser As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''inputPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputPass As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''inputUserDoctores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputUserDoctores As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''inputPassDoctores control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputPassDoctores As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''inputUserPaciente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputUserPaciente As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''inputPassPaciente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inputPassPaciente As Global.System.Web.UI.HtmlControls.HtmlInputPassword
End Class
